fix: as of parsby 1.1, IO can be mutated during parsing
See https://github.com/jolmg/parsby/blob/534f8a95b40cd7102bb55abd2a02ef576a9198da/lib/parsby.rb#L572C11-L572C17

Trace:
IOError: not modifiable string
    # parsby-1.1.1/lib/parsby.rb:572:in `ungetc'
    # parsby-1.1.1/lib/parsby.rb:572:in `ungetc'
    # parsby-1.1.1/lib/parsby.rb:539:in `block in restore'
    # parsby-1.1.1/lib/parsby.rb:539:in `each'