js: fix webpack-dev-server
Currently `bin/webpack-dev-server` raises an error:

> /rails_app/node_modules/webpack-cli/bin/utils/prompt-command.js:46
>    return func(...args);
>           ^
>
> TypeError: Class constructor ServeCommand cannot be invoked without 'new'

It seems this is because webpack-dev-server 4+ stopped being
compatible with webpack 5. So we have to downgrade to webpack-dev-server
3 to fix it.

See https://stackoverflow.com/questions/69046801/brand-new-rails-6-1-4-1-fails-with-webpack-error-typeerror-class-constructor